<?xml version="1.0" encoding="utf-8"?><Database Name="WolfApproveCore.Siammakro-UAT" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-FIE2J6M\SQLEXPRESS;Initial Catalog=WolfApproveCore.Siammakro-UAT;Integrated Security=True" SettingsObjectName="SendAlertEmail.Properties.Settings" SettingsPropertyName="WolfApproveCore_Siammakro_UATConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TRNMemo" Member="TRNMemos">
    <Type Name="TRNMemo">
      <Column Name="MemoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocumentNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TemplateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TemplateType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReportLang" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TemplateDetail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ToPerson" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CcPerson" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TemplateSubject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TTextForm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TAdvanceForm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AutoApprove" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AutoApproveWhen" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ApproverCanEdit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CPositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CPositionTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CPositionEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CDepartmentTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDepartmentEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CDivisionTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDivisionEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RequesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RPositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RPositionTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RPositionEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RDepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RDepartmentTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RDepartmentEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RDivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RDivisionTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RDivisionEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MemoSubject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MTextForm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MAdvancveForm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CurrentApprovalLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LastActionBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LastStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastStatusName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PersonWaitingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonWaiting" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="IsReaded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GroupTemplateName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSTEmployee" Member="MSTEmployees">
    <Type Name="MSTEmployee">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReportToEmpCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SignPicPath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ADTitle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_TRNMemo" Member="v_TRNMemos">
    <Type Name="v_TRNMemo">
      <Column Name="MemoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocumentNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TemplateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TemplateType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReportLang" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TemplateDetail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ToPerson" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CcPerson" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TemplateSubject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TTextForm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AutoApprove" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AutoApproveWhen" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ApproverCanEdit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CPositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CPositionTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CPositionEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CDepartmentTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDepartmentEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CDivisionTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDivisionEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RequesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RPositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RPositionTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RPositionEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RDepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RDepartmentTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RDepartmentEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RDivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RDivisionTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RDivisionEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MemoSubject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MTextForm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CurrentApprovalLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LastActionBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LastStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastStatusName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PersonWaitingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonWaiting" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="IsReaded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GroupTemplateName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRNReferenceDoc" Member="TRNReferenceDocs">
    <Type Name="TRNReferenceDoc">
      <Column Name="RefDocID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemoRefDocID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TemplateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MemoSubject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Seq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowColumn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(15,3)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSTTemplate" Member="MSTTemplates">
    <Type Name="MSTTemplate">
      <Column Name="TemplateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupTemplateName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocumentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isPublic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReportLang" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TemplateDetail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ToId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CcId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TemplateSubject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsTextForm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TextForm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdvanceForm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AutoApprove" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AutoApproveWhen" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ApproverCanEdit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsEdit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isPDFShowInfo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isRequesterEditApproval" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isFormControl" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SpecificEmployeeId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SpecificRoleId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RefTemplate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MultiDeptId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReqAttach" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RefDocColumn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RefDocDisplay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewEmployee" Member="ViewEmployees">
    <Type Name="ViewEmployee">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PositionNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PositionNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DepartmentNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SignPicPath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccountCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DefaultLang" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="RegisteredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ReportToEmpCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DivisionNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DivisionNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ADTitle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRNActionHistory" Member="TRNActionHistories">
    <Type Name="TRNActionHistory">
      <Column Name="ActionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActorName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActionProcess" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ActionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NextApproverID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NextApproverName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SignPicPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ActionStatus" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SignatureId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Platform" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ActorNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ActorNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ActorPositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActorPositionNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ActorPositionNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ActorDepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActorDepartmentNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ActorDepartmentNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ListFilePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DelegateActorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DelegateActorNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DelegateActorNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DelegateActorPositionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DelegateActorPositionNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DelegateActorPositionNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DelegateActorDepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DelegateActorDepartmentNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DelegateActorDepartmentNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HAdvancveForm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSTCompany" Member="MSTCompanies">
    <Type Name="MSTCompany">
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AddressTh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AddressEn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UrlWeb" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UrlLogo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSTDepartment" Member="MSTDepartments">
    <Type Name="MSTDepartment">
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeaderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSTDivision" Member="MSTDivisions">
    <Type Name="MSTDivision">
      <Column Name="DivisionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DivisionCode" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSTMasterData" Member="MSTMasterDatas">
    <Type Name="MSTMasterData">
      <Column Name="MasterId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MasterType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Value1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Value2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Value3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Value4" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Value5" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Seq" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRNAttachFile" Member="TRNAttachFiles">
    <Type Name="TRNAttachFile">
      <Column Name="AttachId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActorName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AttachedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AttachFile" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MemoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DelegateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsMergePDF" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MSTTemplateLogic" Member="MSTTemplateLogics">
    <Type Name="MSTTemplateLogic">
      <Column Name="logicid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TemplateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Seq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="logictype" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="jsonvalue" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRNLineApprove" Member="TRNLineApproves">
    <Type Name="TRNLineApprove">
      <Column Name="LineApproveId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Seq" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PositionTH" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PositionEN" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SignatureId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SignatureTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SignatureEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TemLineId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApproveType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewRole" Member="ViewRoles">
    <Type Name="ViewRole">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RoleNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmpNameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EmpNameTh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MSTEmailTemplate" Member="MSTEmailTemplates">
    <Type Name="MSTEmailTemplate">
      <Column Name="EmailTemplateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TemplateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FormState" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EmailTo" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="EmailCC" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="EmailSubject" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="EmailBody" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>